In [79]:
import pandas as pd
import os

In [80]:
df = pd.read_csv(r'C:\jupyter_projects\ITS\old_data_merge_2\old_data_merge.csv', encoding = 'utf-8-sig')
df.head()

,돌발일시,??코드,돌발시작일시,돌발종료일시,소요시간,돌발구분,돌발상세구분,돌발내용,차로,위도,경도
0,2021-02-24 9:12,NaN,2021-02-24 9:12,2021-02-24 18:00,0 days 08:48:00,0,공사,동광로5길 삼성혈 삼성의원사거리 1차로 주의운전 도로공사 -,1,126.530438,33.503699
1,2021-02-24 10:00,81.0,2021-02-24 9:57,2021-02-24 10:27,0 days 00:29:58,1,사고,애조로 해안동8044 노형동19305 1차로 주의운전 교통사고 -,1,126.470050,33.464721
2,2021-02-24 12:44,NaN,2021-02-24 9:57,2021-02-24 10:27,0 days 00:30:00,1,사고,애조로 해안동8044 노형동19305 1차로 주의운전 교통사고 -,1,126.470050,33.464721
3,2021-02-24 12:45,794.0,2021-02-24 9:57,2021-02-24 10:27,0 days 00:29:58,1,사고,애조로 해안동8044 노형동19305 1차로 주의운전 교통사고 -,1,126.470050,33.464721
4,2021-02-26 15:46,NaN,2021-02-26 15:45,2021-02-26 16:15,0 days 00:30:00,2,기상,지방도1132호선 외도연대마을 그린숲어린이집 1차로 주의운전 강풍 -,1,126.430584,33.492827

In [ ]:
df_season = df.copy()
df_season.head()

### '월' 데이터 추출

In [82]:
df_season['월'] = df_season['돌발일시'].str.slice(5, 7).astype(int)

In [83]:
df_season.head()

,돌발일시,??코드,돌발시작일시,돌발종료일시,소요시간,돌발구분,돌발상세구분,돌발내용,차로,위도,경도,월
0,2021-02-24 9:12,NaN,2021-02-24 9:12,2021-02-24 18:00,0 days 08:48:00,0,공사,동광로5길 삼성혈 삼성의원사거리 1차로 주의운전 도로공사 -,1,126.530438,33.503699,2
1,2021-02-24 10:00,81.0,2021-02-24 9:57,2021-02-24 10:27,0 days 00:29:58,1,사고,애조로 해안동8044 노형동19305 1차로 주의운전 교통사고 -,1,126.470050,33.464721,2
2,2021-02-24 12:44,NaN,2021-02-24 9:57,2021-02-24 10:27,0 days 00:30:00,1,사고,애조로 해안동8044 노형동19305 1차로 주의운전 교통사고 -,1,126.470050,33.464721,2
3,2021-02-24 12:45,794.0,2021-02-24 9:57,2021-02-24 10:27,0 days 00:29:58,1,사고,애조로 해안동8044 노형동19305 1차로 주의운전 교통사고 -,1,126.470050,33.464721,2
4,2021-02-26 15:46,NaN,2021-02-26 15:45,2021-02-26 16:15,0 days 00:30:00,2,기상,지방도1132호선 외도연대마을 그린숲어린이집 1차로 주의운전 강풍 -,1,126.430584,33.492827,2

### '계절' 데이터 추출

In [84]:
df_season['계절'] = (df_season['월'] // 3) % 4

season_mapping = {0 : '겨울', 1 : '봄', 2 : '여름', 3 : '가을'}

df_season['계절'] = df_season['계절'].map(season_mapping)

In [85]:
df_season.head()

,돌발일시,??코드,돌발시작일시,돌발종료일시,소요시간,돌발구분,돌발상세구분,돌발내용,차로,위도,경도,월,계절
0,2021-02-24 9:12,NaN,2021-02-24 9:12,2021-02-24 18:00,0 days 08:48:00,0,공사,동광로5길 삼성혈 삼성의원사거리 1차로 주의운전 도로공사 -,1,126.530438,33.503699,2,겨울
1,2021-02-24 10:00,81.0,2021-02-24 9:57,2021-02-24 10:27,0 days 00:29:58,1,사고,애조로 해안동8044 노형동19305 1차로 주의운전 교통사고 -,1,126.470050,33.464721,2,겨울
2,2021-02-24 12:44,NaN,2021-02-24 9:57,2021-02-24 10:27,0 days 00:30:00,1,사고,애조로 해안동8044 노형동19305 1차로 주의운전 교통사고 -,1,126.470050,33.464721,2,겨울
3,2021-02-24 12:45,794.0,2021-02-24 9:57,2021-02-24 10:27,0 days 00:29:58,1,사고,애조로 해안동8044 노형동19305 1차로 주의운전 교통사고 -,1,126.470050,33.464721,2,겨울
4,2021-02-26 15:46,NaN,2021-02-26 15:45,2021-02-26 16:15,0 days 00:30:00,2,기상,지방도1132호선 외도연대마을 그린숲어린이집 1차로 주의운전 강풍 -,1,126.430584,33.492827,2,겨울

### 돌발 상황 발생 '시간대' 데이터 추출

In [98]:
df_season['상황 발생 시간대'] = df_season['돌발시작일시'].str.slice(11, 13)
df_season['상황 발생 시간대'] = df_season['상황 발생 시간대'].str.replace(':', '')
df_season['상황 발생 시간대'] = df_season['상황 발생 시간대'].astype(int)
df_season['상황 발생 시간대'] = (df_season['상황 발생 시간대'] // 6) % 4

time_zone_mapping = {0 : '새벽', 1 : '오전', 2 : '오후', 3 : '저녁'}

df_season['상황 발생 시간대'] = df_season['상황 발생 시간대'].map(time_zone_mapping)

df_season.head()

,돌발일시,??코드,돌발시작일시,돌발종료일시,소요시간,돌발구분,돌발상세구분,돌발내용,차로,위도,경도,월,계절,상황 발생 시간대
0,2021-02-24 9:12,NaN,2021-02-24 9:12,2021-02-24 18:00,0 days 08:48:00,0,공사,동광로5길 삼성혈 삼성의원사거리 1차로 주의운전 도로공사 -,1,126.530438,33.503699,2,겨울,오전
1,2021-02-24 10:00,81.0,2021-02-24 9:57,2021-02-24 10:27,0 days 00:29:58,1,사고,애조로 해안동8044 노형동19305 1차로 주의운전 교통사고 -,1,126.470050,33.464721,2,겨울,오전
2,2021-02-24 12:44,NaN,2021-02-24 9:57,2021-02-24 10:27,0 days 00:30:00,1,사고,애조로 해안동8044 노형동19305 1차로 주의운전 교통사고 -,1,126.470050,33.464721,2,겨울,오전
3,2021-02-24 12:45,794.0,2021-02-24 9:57,2021-02-24 10:27,0 days 00:29:58,1,사고,애조로 해안동8044 노형동19305 1차로 주의운전 교통사고 -,1,126.470050,33.464721,2,겨울,오전
4,2021-02-26 15:46,NaN,2021-02-26 15:45,2021-02-26 16:15,0 days 00:30:00,2,기상,지방도1132호선 외도연대마을 그린숲어린이집 1차로 주의운전 강풍 -,1,126.430584,33.492827,2,겨울,오후

In [99]:
df_season['돌발구분'] = df_season['돌발구분'].astype('int')
df_season.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   돌발일시       940 non-null    object
 1   ??코드       133 non-null    float64
 2   돌발시작일시     940 non-null    object
 3   돌발종료일시     940 non-null    object
 4   소요시간       940 non-null    object
 5   돌발구분       940 non-null    int32
 6   돌발상세구분     940 non-null    object
 7   돌발내용       940 non-null    object
 8   차로         940 non-null    object
 9   위도         940 non-null    float64
 10  경도         940 non-null    float64
 11  월          940 non-null    int32
 12  계절         940 non-null    object
 13  상황 발생 시간대  940 non-null    object
dtypes: float64(3), int32(2), object(9)
memory usage: 95.6+ KB

계절 별 돌발 상황 빈도
계절
봄     353
여름    294
가을    185
겨울    108
Name: count, dtype: int64
============================================================
시간대 별 돌발 상황 빈도
상황 발생 시간대
오전    495
오후    382
저녁     58
새벽      5
Name: count, dtype: int64
============================================================
돌발 상황 별 빈도
돌발구분
0    650
1    186
2    104
Name: count, dtype: int64
============================================================
돌발 상황 상세 구분
돌발상세구분
공사         650
사고         186
통제          81
기상          10
행사          10
신호기 고장       3
Name: count, dtype: int64

### 도로명 추출

In [101]:
def extract_road_name(text):
    road_name = text.split()
    if '>' in road_name[0]:
        return road_name[1]
    return road_name[0]

def road_name(df):
    df_season['돌발내용'] = df_season['돌발내용'].astype(str)
    df_season['도로명'] = df_season['돌발내용'].apply(extract_road_name)
    return df_season

In [102]:
df_season = road_name(df_season)

df_season.head()

,돌발일시,??코드,돌발시작일시,돌발종료일시,소요시간,돌발구분,돌발상세구분,돌발내용,차로,위도,경도,월,계절,상황 발생 시간대,도로명
0,2021-02-24 9:12,NaN,2021-02-24 9:12,2021-02-24 18:00,0 days 08:48:00,0,공사,동광로5길 삼성혈 삼성의원사거리 1차로 주의운전 도로공사 -,1,126.530438,33.503699,2,겨울,오전,동광로5길
1,2021-02-24 10:00,81.0,2021-02-24 9:57,2021-02-24 10:27,0 days 00:29:58,1,사고,애조로 해안동8044 노형동19305 1차로 주의운전 교통사고 -,1,126.470050,33.464721,2,겨울,오전,애조로
2,2021-02-24 12:44,NaN,2021-02-24 9:57,2021-02-24 10:27,0 days 00:30:00,1,사고,애조로 해안동8044 노형동19305 1차로 주의운전 교통사고 -,1,126.470050,33.464721,2,겨울,오전,애조로
3,2021-02-24 12:45,794.0,2021-02-24 9:57,2021-02-24 10:27,0 days 00:29:58,1,사고,애조로 해안동8044 노형동19305 1차로 주의운전 교통사고 -,1,126.470050,33.464721,2,겨울,오전,애조로
4,2021-02-26 15:46,NaN,2021-02-26 15:45,2021-02-26 16:15,0 days 00:30:00,2,기상,지방도1132호선 외도연대마을 그린숲어린이집 1차로 주의운전 강풍 -,1,126.430584,33.492827,2,겨울,오후,지방도1132호선

### 제주시 / 서귀포시 구분

In [105]:
import chardet

# 파일 인코딩 확인
def detect_encoding(file_path):
    with open(file_path, 'rb') as f:
        raw_data = f.read()
    result = chardet.detect(raw_data)
    return result['encoding']
   

folder_path = r'C:\jupyter_projects\ITS\jeju_road_name'

for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)
    print(f"Processing file : {file_path}")

     # 파일 인코딩 형식 확인
    encoding = detect_encoding(file_path)

    print(encoding)

Processing file : C:\jupyter_projects\ITS\jeju_road_name\jeju.csv
EUC-KR
Processing file : C:\jupyter_projects\ITS\jeju_road_name\seogwipo.csv
EUC-KR

In [133]:
df_jeju = pd.read_csv(r'C:\jupyter_projects\ITS\jeju_road_name\jeju_2.csv', encoding = encoding)
df_seogwipo = pd.read_csv(r'C:\jupyter_projects\ITS\jeju_road_name\seogwipo_2.csv', encoding = encoding)

# road_jeju = df_jeju['도로명주소'].str.split()
# road_seogwipo = df_seogwipo['도로명주소'].str.split()

road_jeju = df_jeju['도로명']
road_seogwipo = df_seogwipo['도로명']

In [ ]:
road_name_jeju = []
road_name_seogwipo = []

for road_index in range(len(road_jeju)):
    if "로" in road_jeju[road_index][1] or "길" in road_jeju[road_index][1]:
        road_name_jeju.append(road_jeju[road_index][1])
    else:
        road_name_jeju.append(road_jeju[road_index][2])

for road_index in range(len(road_seogwipo)):
    if "로" in road_seogwipo[road_index][1] or "길" in road_seogwipo[road_index][1]:
        road_name_seogwipo.append(road_seogwipo[road_index][1])
    else:
        road_name_seogwipo.append(road_seogwipo[road_index][2])

road_name_jeju = set(road_name_jeju)

road_name_seogwipo = set(road_name_seogwipo)

In [134]:
jeju_2 = df_jeju['도로명']
jeju_2 = jeju_2.values
jeju_2 = jeju_2.tolist()

seogwipo_2 = df_seogwipo['도로명']
seogwipo_2 = seogwipo_2.values
seogwipo_2 = seogwipo_2.tolist()

In [135]:
# 사용 X
def seperate_jeju(df_season, road_name_jeju, road_name_seogwipo):

    df['지역구분'] = None

    for idx, row in df_season.iterrows():
        if row['도로명'] in road_name_jeju:
            df_season.at[idx, '지역구분'] = '제주시'
        elif row['도로명'] in road_name_seogwipo:
            df_season.at[idx, '지역구분'] = '서귀포시'
        else:
            df_season.at[idx, '지역구분'] = row['도로명']

    return df_season


def seperate_jeju_2(df_season, jeju_2, seogwipo_2):

    df['지역구분'] = None

    for idx, row in df_season.iterrows():
        if row['도로명'] in jeju_2:
            df_season.at[idx, '지역구분'] = '제주시'
        elif row['도로명'] in seogwipo_2:
            df_season.at[idx, '지역구분'] = '서귀포시'
        else:
            df_season.at[idx, '지역구분'] = row['도로명']

    return df_season

In [173]:
# '월', '계절', '도로명', '지역구분' column까지 파일 저장

df_season = seperate_jeju_2(df_season, jeju_2, seogwipo_2)

df_season

save_folder_path = r'C:\jupyter_projects\ITS\old_data_merge_2'
save_path = os.path.join(save_folder_path, filename)


df_season.to_csv('C:\\jupyter_projects\\ITS\\old_data_merge_2\\old_data_merge_fin.csv', index = False, header = True, encoding = encoding)

In [169]:
from collections import Counter

# 열 별 전체 데이터 개수
print(df_season.count())
print('')
print('=' * 60)
print('')

# 계절 count
print('계절 별 돌발 상황 빈도 : ', df_season['계절'].count())
print('봄 : ', Counter(df_season['계절'])['봄'], ', 비율 : ' , round(Counter(df_season['계절'])['봄'] / 940, 3))
print('여름 : ', Counter(df_season['계절'])['여름'], ', 비율 : ' , round(Counter(df_season['계절'])['여름'] / 940, 3))
print('가을 : ', Counter(df_season['계절'])['가을'], ', 비율 : ' , round(Counter(df_season['계절'])['가을'] / 940, 3))
print('겨울 : ', Counter(df_season['계절'])['겨울'], ', 비율 : ' , round(Counter(df_season['계절'])['겨울'] / 940, 3))
# print(df_season['계절'].value_counts())

print('')
print('=' * 60)
print('')

# 시간대 count
print('시간대 별 돌발 상황 빈도 : ', df_season['상황 발생 시간대'].count())
print('오전 : ', Counter(df_season['상황 발생 시간대'])['오전'], ', 비율 : ', round(Counter(df_season['상황 발생 시간대'])['오전'] / 940, 3))
print('오후 : ', Counter(df_season['상황 발생 시간대'])['오후'], ', 비율 : ', round(Counter(df_season['상황 발생 시간대'])['오후'] / 940, 3))
print('저녁 : ', Counter(df_season['상황 발생 시간대'])['저녁'], ', 비율 : ', round(Counter(df_season['상황 발생 시간대'])['저녁'] / 940, 3))
print('새벽 : ', Counter(df_season['상황 발생 시간대'])['새벽'], ', 비율 : ', round(Counter(df_season['상황 발생 시간대'])['새벽'] / 940, 3))
# print(df_season['상황 발생 시간대'].value_counts())
print('')
print('=' * 60)
print('')

# 돌발 상황 count
print('돌발 상황 별 빈도 : ', df_season['돌발구분'].count())
print('0 : ', Counter(df_season['돌발구분'])[0], '비율 : ', round(Counter(df_season['돌발구분'])[0] / 940, 3))
print('1 : ', Counter(df_season['돌발구분'])[1], '비율 : ', round(Counter(df_season['돌발구분'])[1] / 940, 3))
print('2 : ', Counter(df_season['돌발구분'])[2], '비율 : ', round(Counter(df_season['돌발구분'])[2] / 940, 3))
# print(df_season['돌발구분'].value_counts())
print('')
print('=' * 60)
print('')

# 돌발 상세 구분 count
print('돌발 상황 상세 구분 : ', df_season['돌발상세구분'].count())
print('공사 : ', Counter(df_season['돌발상세구분'])['공사 '], '비율 : ', round(Counter(df_season['돌발상세구분'])['공사 '] / 940, 3))
print('사고 : ', Counter(df_season['돌발상세구분'])['사고 '], '비율 : ', round(Counter(df_season['돌발상세구분'])['사고 '] / 940, 3))
print('통제 : ', Counter(df_season['돌발상세구분'])['통제 '], '비율 : ', round(Counter(df_season['돌발상세구분'])['통제 '] / 940, 3))
print('기상 : ', Counter(df_season['돌발상세구분'])['기상 '], '비율 : ', round(Counter(df_season['돌발상세구분'])['기상 '] / 940, 3))
print('행사 : ', Counter(df_season['돌발상세구분'])['행사 '], '비율 : ', round(Counter(df_season['돌발상세구분'])['행사 '] / 940, 3))
print('신호기 고장 : ', Counter(df_season['돌발상세구분'])['신호기 고장 '], '비율 : ', round(Counter(df_season['돌발상세구분'])['신호기 고장 '] / 940, 3))
# print(df_season['돌발상세구분'].value_counts())
print('')
print('=' * 60)
print('')

# 도로명 count
print('돌발상황 발생 도로명 구분')
print(df_season['도로명'].value_counts())
print('')
print('=' * 60)
print('')

# 지역 count
print('돌발상황 발생 지역 구분')
print(df_season['지역구분'].value_counts())

돌발일시         940
??코드         133
돌발시작일시       940
돌발종료일시       940
소요시간         940
돌발구분         940
돌발상세구분       940
돌발내용         940
차로           940
위도           940
경도           940
월            940
계절           940
상황 발생 시간대    940
도로명          940
지역구분         940
dtype: int64

============================================================

계절 별 돌발 상황 빈도 :  940
봄 :  353 , 비율 :  0.376
여름 :  294 , 비율 :  0.313
가을 :  185 , 비율 :  0.197
겨울 :  108 , 비율 :  0.115

============================================================

시간대 별 돌발 상황 빈도 :  940
오전 :  495 , 비율 :  0.527
오후 :  382 , 비율 :  0.406
저녁 :  58 , 비율 :  0.062
새벽 :  5 , 비율 :  0.005

============================================================

돌발 상황 별 빈도 :  940
0 :  650 비율 :  0.691
1 :  186 비율 :  0.198
2 :  104 비율 :  0.111

============================================================

돌발 상황 상세 구분 :  940
공사 :  650 비율 :  0.691
사고 :  186 비율 :  0.198
통제 :  81 비율 :  0.086
기상 :  10 비율 :  0.011
행사 :  10 비율 :  0.011
신호기 고장 :  3 비율 :  0.003

============================================================

돌발상황 발생 도로명 구분
도로명
지방도1132호선      137
지방도1136호선       74
지방도1139호선       47
국가지원지방도97호선     38
애조로             33
              ...
성신로              1
중문로              1
도근내길             1
도리로              1
산록북로             1
Name: count, Length: 197, dtype: int64

============================================================

돌발상황 발생 지역 구분
지역구분
제주시            386
서귀포시           150
지방도1132호선      137
지방도1136호선       74
지방도1139호선       47
국가지원지방도97호선     38
지방도1131호선       16
시청로             13
범섬길              4
가시머리길            4
일주도로             3
미래1로             3
오복8로             3
하산상로             3
문화로              3
지방도1112호선        2
동광초등길            2
여명로              2
중산간도로            2
제주대학교            2
제일교사거리           2
양지1로             2
우정서11로           2
버으내교차로           2
인정오름길            2
제주시청민원실          2
가야대로             2
새통길              2
서호1로             1
사계해안로            1
돈내코1로            1
토평4로             1
토평동              1
동광초등3로           1
지방도              1
문부1로             1
제일교              1
오일장길             1
돔베낭길             1
동홍새싹길            1
지방도1115호선        1
월평로142           1
516도로            1
다랑굿7로            1
수덕7로             1
사대부고서로           1
월대3로             1
용운로              1
퍼시픽호텔            1
솔동산길             1
인화북5로            1
앞거리길             1
물통삼거리            1
지방도1117호선        1
축산마을길            1
삼무2로             1
주공로              1
남태안로             1
Name: count, dtype: int64